name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install isort black

      - name: Check import order with isort
        run: isort . --check

      - name: Check formatting with black
        run: black . --check

      - name: Test Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false